#!/bin/sh
set -e

echo "[AIFW] =============================="
echo "[AIFW] AI Firewall Gateway Starting"
echo "[AIFW] =============================="

# ── Enable IP Forwarding ─────────────────────────────────────
# On Docker Desktop (Windows/macOS), /proc/sys is read-only.
# We use sysctls in docker-compose.yml as the primary method.
# This is a fallback for Linux hosts with privileged mode.
if echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null; then
    echo "[AIFW] IP forwarding enabled via /proc/sys"
else
    echo "[AIFW] WARN: Cannot write /proc/sys (read-only). Relying on sysctls from docker-compose."
fi

# Enable route_localnet on all interfaces to allow transparent DNAT to 127.0.0.1
for i in /proc/sys/net/ipv4/conf/*/route_localnet; do
    echo 1 > "$i" 2>/dev/null || true
done
echo "[AIFW] route_localnet enabled on all interfaces"

# ── Flush existing rules ─────────────────────────────────────
iptables -t nat -F 2>/dev/null || true
iptables -F FORWARD 2>/dev/null || true

# ── FORWARD: allow all forwarded traffic ─────────────────────
iptables -P FORWARD ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -j ACCEPT

# ── MASQUERADE: for return traffic ───────────────────────────
iptables -t nat -A POSTROUTING -j MASQUERADE

# ── Create AIFW chain for dynamic rules ──────────────────────
# The backend will dynamically add DNAT rules to this chain
iptables -t nat -N AIFW_INTERCEPT 2>/dev/null || iptables -t nat -F AIFW_INTERCEPT
iptables -t nat -A PREROUTING -j AIFW_INTERCEPT

echo "[AIFW] iptables gateway rules configured"
echo "[AIFW] Waiting for dynamic intercept rules from backend..."

# ── Configure ModSecurity ────────────────────────────────────
# Dynamically generate the override config based on env vars

MODSEC_MODE=${MODSEC_RULE_ENGINE:-DetectionOnly}
echo "[AIFW] ModSecurity Mode: $MODSEC_MODE"

cat > /etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf <<EOF
# Generated by entrypoint script
SecRuleEngine $MODSEC_MODE

# Log everything (On) instead of RelevantOnly, so we can see successful attacks in DetectionOnly mode
SecAuditEngine On
SecAuditLogType Serial
SecAuditLog /var/log/modsecurity/audit.log
SecAuditLogFormat JSON
SecAuditLogParts ABCDEFHZ

# Tuning
SecAction "id:900110,phase:1,pass,t:none,nolog,setvar:tx.inbound_anomaly_score_threshold=3"
SecAction "id:900111,phase:1,pass,t:none,nolog,setvar:tx.outbound_anomaly_score_threshold=3"
SecAction "id:900000,phase:1,pass,t:none,nolog,setvar:tx.blocking_paranoia_level=2"
EOF

echo "[AIFW] ModSecurity override config written"



# ── Health check endpoint (port 9999) ────────────────────────
# Nginx main config listens on port 9999 for health + management
# Dynamic proxy ports are added by the backend via docker exec

# Delegate to the original entrypoint to initialize ModSecurity and start Nginx
exec /docker-entrypoint.sh "$@"
